import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

import { useRef } from 'react'
import { About, Banner, Contact, Footer, Header, Projects } from '@/components'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const aboutRef = useRef(null);
  const projectRef = useRef(null);
  const aboutScroll = () => {
    aboutRef.current.scrollIntoView()
  }
  const projectScroll = () => {
    projectRef.current.scrollIntoView()
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header projectScroll={projectScroll} aboutScroll={aboutScroll} />
      <Banner />
      <Projects projectRef={projectRef} />
      <About aboutRef={aboutRef} />
      <Contact />
      <Footer />
    </>
  )
}
